spring.application.name=spring_security

spring.security.user.name = navin
spring.security.user.password = hatim00

spring.datasource.url = jdbc:postgresql://db.mtgsvtaiqstrhroiysdd.supabase.co:5432/postgres?user=postgres&password=uWN4$e*4yJi6JHv
spring.datasource.username = postgres.mtgsvtaiqstrhroiysdd
spring.datasource.password = uWN4$e*4yJi6JHv
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true